# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mianwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Video_Retrieval import GetFeatures, Search_Process


class Ui_MainWindow(QtWidgets.QMainWindow):
    SAMPLE_PATH = ''
    SAMPLE_NAME = ''

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 110, 771, 441))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 771, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.viewlayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.viewlayout.setContentsMargins(10, 10, 10, 10)
        self.viewlayout.setSpacing(15)
        self.viewlayout.setObjectName("viewlayout")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.viewlayout.addWidget(self.graphicsView_4, 2, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.viewlayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.viewlayout.addWidget(self.graphicsView_7, 4, 0, 1, 1)
        self.graphicsView_1 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.viewlayout.addWidget(self.graphicsView_1, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.viewlayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.viewlayout.addWidget(self.graphicsView_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.viewlayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.viewlayout.addWidget(self.graphicsView_8, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.viewlayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.viewlayout.addWidget(self.graphicsView_5, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.viewlayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.viewlayout.addWidget(self.graphicsView_3, 0, 2, 1, 1)
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.viewlayout.addWidget(self.graphicsView_9, 4, 2, 1, 1)
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.viewlayout.addWidget(self.graphicsView_6, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.viewlayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.viewlayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.viewlayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.viewlayout.addWidget(self.label_8, 5, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filepath_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.filepath_label.setLineWidth(0)
        self.filepath_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.filepath_label.setOpenExternalLinks(False)
        self.filepath_label.setObjectName("filepath_label")
        self.horizontalLayout.addWidget(self.filepath_label)
        self.filepath_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.filepath_lineEdit.setObjectName("filepath_lineEdit")
        self.horizontalLayout.addWidget(self.filepath_lineEdit)
        self.choosefile_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.choosefile_btn.setObjectName("choosefile_btn")
        self.horizontalLayout.addWidget(self.choosefile_btn)
        self.confirm_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.confirm_btn.setObjectName("confirm_btn")
        self.horizontalLayout.addWidget(self.confirm_btn)
        # MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_about = QtWidgets.QMenu(self.menubar)
        self.menu_about.setObjectName("menu_about")
        # MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        self.actionopen_file = QtWidgets.QAction(MainWindow)
        self.actionopen_file.setIconText("打开文件")
        self.actionopen_file.setIconVisibleInMenu(True)
        self.actionopen_file.setObjectName("actionopen_file")
        self.menu_file.addAction(self.actionopen_file)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_about.menuAction())

        self.choosefile_btn.clicked.connect(self.OpenFile)
        self.confirm_btn.clicked.connect(self.SearchVideo)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "视频检索Demo"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.filepath_label.setText(_translate("MainWindow", "样例视频："))
        self.choosefile_btn.setText(_translate("MainWindow", "浏览"))
        self.confirm_btn.setText(_translate("MainWindow", "搜索"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_about.setTitle(_translate("MainWindow", "关于"))
        self.actionopen_file.setText(_translate("MainWindow", "打开文件"))

    def OpenFile(self):
        filepath, _ = QtWidgets.QFileDialog.getOpenFileName(None, '打开文件', './', "视频文件(*.avi *.mp4)")
        self.SAMPLE_PATH = filepath
        self.SAMPLE_NAME = filepath.split('/')[-1]
        self.filepath_lineEdit.setText(self.SAMPLE_NAME)

    def SearchVideo(self):
        if self.SAMPLE_PATH != '':
            print(self.SAMPLE_PATH)
            # GetFeatures.get_features(self.SAMPLE_PATH)
        else:
            unselect_message = QtWidgets.QErrorMessage(self, "请先选择样例视频。")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
